### ISSUE TITLE
how to change kasm_vnc login account?

### ISSUE THREAD

**Issue by qpb8023** [kasmtech/workspaces-images#2]
![屏幕截图 2021-07-09 111138](https://user-images.githubusercontent.com/27752049/125018037-dc4a9380-e0a6-11eb-80b9-080029a7c619.png)

**Comment by mmcclaskey** [comment]
Hello, 

It looks like the username is hard coded to kasm_user. The reason for this is that these images are intended to be used within the Kasm Workspaces framework and the KasmVNC user is abstracted when the container is orchestrated by Kasm Workspaces. But, we could easily modify the VNC startup script to use an environmental variable rather than a hard coded username. I've opened up an issue on the core images project, since that needs to be added to the core image and will close this issue....

https://github.com/kasmtech/workspaces-core-images/issues/1

https://github.com/kasmtech/workspaces-core-images/blob/0bb3cd1a0f0b39ef11fa2b63e1a6ab3cbac5ec75/src/common/startup_scripts/vnc_startup.sh#L177

**Comment by jerrywoo96** [comment]
So... what is the environment variable to change the login username? The docker run commands arn't updated to specify a different vnc user log in. And i cannot find any existing images that that mention this environment variable to change the vnc login username.
