### ISSUE TITLE
How to build an image based on the CentOS core image?

### ISSUE THREAD

**Issue by hamedsbt** [kasmtech/workspaces-images#30]
Hello, I wonder what the role of Centos, Oracle, and SUSE core images is? 
I examined several workspace-images and discovered that they were built on an Ubuntu base. 
How to build a workspace-images based on the CentOS core? 
Is it enough to change only the one line of the Docker file? (I'm referring to changing the core image name). 
Thank you in advance.

**Comment by j-travis** [comment]
The CentOS, Oracle and OpenSUSE core images are available so that folks can build derivative images based on them.

For example we have derivative "desktop" images based on all these

- CentOS
  - https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-centos-7-desktop
  - https://hub.docker.com/r/kasmweb/centos-7-desktop
- Oracle
  - https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-oracle-8-desktop
  - https://hub.docker.com/r/kasmweb/oracle-8-desktop
- OpenSUSE
  - https://github.com/kasmtech/workspaces-images/blob/develop/dockerfile-kasm-opensuse-15-desktop
  - https://hub.docker.com/r/kasmweb/opensuse-15-desktop


However, as you've seen most of our derivitive app-based images in the `workspaces-images` repo are based on ubuntu. This is generally for consistency.  You are free to make your own images based on any of the Core images which is why we publish all of them open source

Here are resources to get you started

- https://kasmweb.com/docs/latest/how_to/building_images.html
- https://www.youtube.com/watch?v=BGP69_f1wq0
- https://www.youtube.com/watch?v=YesDodQ2Y7o
