### ISSUE TITLE
Slack workspace requires app to be updated

### ISSUE THREAD

**Issue by dgagnon720** [kasmtech/workspaces-images#41]
Hi, I'm new to Kasm, I installed it yesterday and I'm testing today.  I was able to add the slack workspace, but once launched, it requires an update before launching the app.  I tried to do the update myself in the workspace, but it didn't work.  Did I miss something?

Thank you.

**Comment by j-travis** [comment]
Sorry, we stopped maintaining a slack image a while ago because of compatibility issues. It hasn't been published for the last several versions of Workspaces.

You can see more details here and potential work arounds if you want to try and build it yourself:
https://github.com/kasmtech/workspaces-issues/issues/192
