### ISSUE TITLE
file not found in new build

### ISSUE THREAD

**Issue by glw** [kasmtech/workspaces-images#42]
Hi Im getting an error for a missing file. Used `dockerfile-kasm-ubuntu-jammy-dind` as the base file.

Dockerfile changes were to arg base tag and image only for testing:

`ARG BASE_TAG="1.12.0-rolling"`
`ARG BASE_IMAGE="core-ubuntu-jammy"`

Ran docker like this.
`$ docker build -t glw/geokasm -f Dockerfile .`

`
Error:
Step 10/33 : COPY ./src/ubuntu/install/dind $INST_SCRIPTS/dind/
COPY failed: file not found in build context or excluded by .dockerignore: stat src/ubuntu/install/dind: file does not exist
`

Is the dind version not available for jammy at your latest tag version?

Thanks!

**Comment by j-travis** [comment]
Hi, 
The last line is telling you exactly what the problem is.

The dockerfile is trying to COPY files from a location ` ./src/ubuntu/install/dind`  but it doesnt exist. 

My guess is that you have copied instructions from our dockerfiles into a new one, but are not in the same directory, thus this copy fails. Notice the layout of the repo. There is a `src` directory along side the dockerfiles. https://github.com/kasmtech/workspaces-images.

I recommend walking through the following guides in order to help you understand how to work with custom images in the Kasm ecosystem, and how to utilize our example repos:

1. https://kasmweb.com/docs/latest/how_to/building_images.html
2. https://www.youtube.com/watch?v=BGP69_f1wq0
3. https://www.youtube.com/watch?v=YesDodQ2Y7o

Hope this helps

**Comment by glw** [comment]
Ah ok the youtube video on creating custom images really cleared things up. Thanks!
