### ISSUE TITLE
Request whatsapp image

### ISSUE THREAD

**Issue by sojab0on** [kasmtech/workspaces-images#7]
Is it posible to create a image where for example a whatsapp web client.

I could net get a dockerfile running to get it build and running.

**Comment by mmcclaskey** [comment]
We can point you in the right direction. According to this article, there is no official Whatsapp app for linux, but there is an unofficial app "whatsdesk", which appears to be an ElectronJS application. The standard install uses a snap, which cant be used inside a Kasm Workspaces install because a snap is a container in and of itself. But looking at the source code for whatsdesk, there is a [dockerfile](https://gitlab.com/zerkc/whatsdesk/-/blob/master/dockerfile) that shows how the app is built with npm and ran inside that container. That being said, it should be possible to create a Kasm Workspaces container that runs this app. An alternative is to use our Chrome image, run Chrome in Kiosk mode and auto navigate to whatsapp. 

https://itsfoss.com/whatsapp-linux-desktop/
